// flow-typed signature: 1c657e1cd278b46adb507c321d1f308b
// flow-typed version: <<STUB>>/html_v1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html/bin/html' {
  declare module.exports: any;
}

declare module 'html/lib/html' {
  declare module.exports: any;
}

declare module 'html/src/html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html/bin/html.js' {
  declare module.exports: $Exports<'html/bin/html'>;
}
declare module 'html/lib/html.js' {
  declare module.exports: $Exports<'html/lib/html'>;
}
declare module 'html/src/html.js' {
  declare module.exports: $Exports<'html/src/html'>;
}
