// flow-typed signature: cf46b9a1ac63fea52bbd8c76fbbd0612
// flow-typed version: <<STUB>>/kinto-http_v^4.3.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kinto-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kinto-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kinto-http/demo/kinto-http.noshim' {
  declare module.exports: any;
}

declare module 'kinto-http/dist/kinto-http' {
  declare module.exports: any;
}

declare module 'kinto-http/dist/kinto-http.min' {
  declare module.exports: any;
}

declare module 'kinto-http/dist/kinto-http.noshim' {
  declare module.exports: any;
}

declare module 'kinto-http/dist/moz-kinto-http-client' {
  declare module.exports: any;
}

declare module 'kinto-http/fx-src/index' {
  declare module.exports: any;
}

declare module 'kinto-http/fx-src/jsm_prefix' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/base' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/batch' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/bucket' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/collection' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/endpoint' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/errors' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/http' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/index' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/requests' {
  declare module.exports: any;
}

declare module 'kinto-http/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kinto-http/demo/kinto-http.noshim.js' {
  declare module.exports: $Exports<'kinto-http/demo/kinto-http.noshim'>;
}
declare module 'kinto-http/dist/kinto-http.js' {
  declare module.exports: $Exports<'kinto-http/dist/kinto-http'>;
}
declare module 'kinto-http/dist/kinto-http.min.js' {
  declare module.exports: $Exports<'kinto-http/dist/kinto-http.min'>;
}
declare module 'kinto-http/dist/kinto-http.noshim.js' {
  declare module.exports: $Exports<'kinto-http/dist/kinto-http.noshim'>;
}
declare module 'kinto-http/dist/moz-kinto-http-client.js' {
  declare module.exports: $Exports<'kinto-http/dist/moz-kinto-http-client'>;
}
declare module 'kinto-http/fx-src/index.js' {
  declare module.exports: $Exports<'kinto-http/fx-src/index'>;
}
declare module 'kinto-http/fx-src/jsm_prefix.js' {
  declare module.exports: $Exports<'kinto-http/fx-src/jsm_prefix'>;
}
declare module 'kinto-http/lib/base.js' {
  declare module.exports: $Exports<'kinto-http/lib/base'>;
}
declare module 'kinto-http/lib/batch.js' {
  declare module.exports: $Exports<'kinto-http/lib/batch'>;
}
declare module 'kinto-http/lib/bucket.js' {
  declare module.exports: $Exports<'kinto-http/lib/bucket'>;
}
declare module 'kinto-http/lib/collection.js' {
  declare module.exports: $Exports<'kinto-http/lib/collection'>;
}
declare module 'kinto-http/lib/endpoint.js' {
  declare module.exports: $Exports<'kinto-http/lib/endpoint'>;
}
declare module 'kinto-http/lib/errors.js' {
  declare module.exports: $Exports<'kinto-http/lib/errors'>;
}
declare module 'kinto-http/lib/http.js' {
  declare module.exports: $Exports<'kinto-http/lib/http'>;
}
declare module 'kinto-http/lib/index.js' {
  declare module.exports: $Exports<'kinto-http/lib/index'>;
}
declare module 'kinto-http/lib/requests.js' {
  declare module.exports: $Exports<'kinto-http/lib/requests'>;
}
declare module 'kinto-http/lib/utils.js' {
  declare module.exports: $Exports<'kinto-http/lib/utils'>;
}
