// flow-typed signature: e49d06281f1b7bbb71973eb01191d8f4
// flow-typed version: <<STUB>>/kinto-node-test-server_v1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kinto-node-test-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kinto-node-test-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kinto-node-test-server/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kinto-node-test-server/index' {
  declare module.exports: $Exports<'kinto-node-test-server'>;
}
declare module 'kinto-node-test-server/index.js' {
  declare module.exports: $Exports<'kinto-node-test-server'>;
}
declare module 'kinto-node-test-server/test.js' {
  declare module.exports: $Exports<'kinto-node-test-server/test'>;
}
