// flow-typed signature: 347bf1a9fdd21a31ae90ae3f13d7cac0
// flow-typed version: <<STUB>>/mocha-generators_v^2.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-generators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-generators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mocha-generators/index' {
  declare module.exports: $Exports<'mocha-generators'>;
}
declare module 'mocha-generators/index.js' {
  declare module.exports: $Exports<'mocha-generators'>;
}
