// flow-typed signature: 7ca0ce78ac3825dc652f6985dc2625e8
// flow-typed version: <<STUB>>/react-breadcrumbs_v^2.1.4/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-breadcrumbs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-breadcrumbs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-breadcrumbs/demo/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/app' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/crumb-route' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/events' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/friends' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/index' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/src/locations' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/webpack.dev' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/demo/webpack.prod' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/dist/react-breadcrumbs.min' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/src/breadcrumb' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/src/breadcrumbs' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/src/index' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/src/store' {
  declare module.exports: any;
}

declare module 'react-breadcrumbs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-breadcrumbs/demo/dist/bundle.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/dist/bundle'>;
}
declare module 'react-breadcrumbs/demo/src/app.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/app'>;
}
declare module 'react-breadcrumbs/demo/src/crumb-route.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/crumb-route'>;
}
declare module 'react-breadcrumbs/demo/src/events.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/events'>;
}
declare module 'react-breadcrumbs/demo/src/friends.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/friends'>;
}
declare module 'react-breadcrumbs/demo/src/index.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/index'>;
}
declare module 'react-breadcrumbs/demo/src/locations.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/src/locations'>;
}
declare module 'react-breadcrumbs/demo/webpack.dev.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/webpack.dev'>;
}
declare module 'react-breadcrumbs/demo/webpack.prod.js' {
  declare module.exports: $Exports<'react-breadcrumbs/demo/webpack.prod'>;
}
declare module 'react-breadcrumbs/dist/react-breadcrumbs.min.js' {
  declare module.exports: $Exports<'react-breadcrumbs/dist/react-breadcrumbs.min'>;
}
declare module 'react-breadcrumbs/src/breadcrumb.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/src/breadcrumb'>;
}
declare module 'react-breadcrumbs/src/breadcrumbs.jsx' {
  declare module.exports: $Exports<'react-breadcrumbs/src/breadcrumbs'>;
}
declare module 'react-breadcrumbs/src/index.js' {
  declare module.exports: $Exports<'react-breadcrumbs/src/index'>;
}
declare module 'react-breadcrumbs/src/store.js' {
  declare module.exports: $Exports<'react-breadcrumbs/src/store'>;
}
declare module 'react-breadcrumbs/webpack.config.js' {
  declare module.exports: $Exports<'react-breadcrumbs/webpack.config'>;
}
