// flow-typed signature: 34b964bdb26d56295231cfe647274536
// flow-typed version: <<STUB>>/react-jsonschema-form_v^1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jsonschema-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jsonschema-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jsonschema-form/dist/react-jsonschema-form' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/ErrorList' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/ArrayField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/BooleanField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/DescriptionField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/index' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/NumberField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/ObjectField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/SchemaField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/StringField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/TitleField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/fields/UnsupportedField' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/Form' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/AltDateTimeWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/AltDateWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/BaseInput' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/CheckboxesWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/CheckboxWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/ColorWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/DateTimeWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/DateWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/EmailWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/FileWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/HiddenWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/index' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/PasswordWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/RadioWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/RangeWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/SelectWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/TextareaWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/TextWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/UpDownWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/components/widgets/URLWidget' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/index' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/utils' {
  declare module.exports: any;
}

declare module 'react-jsonschema-form/lib/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jsonschema-form/dist/react-jsonschema-form.js' {
  declare module.exports: $Exports<'react-jsonschema-form/dist/react-jsonschema-form'>;
}
declare module 'react-jsonschema-form/lib/components/ErrorList.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/ErrorList'>;
}
declare module 'react-jsonschema-form/lib/components/fields/ArrayField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/ArrayField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/BooleanField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/BooleanField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/DescriptionField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/DescriptionField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/index.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/index'>;
}
declare module 'react-jsonschema-form/lib/components/fields/NumberField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/NumberField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/ObjectField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/ObjectField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/SchemaField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/SchemaField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/StringField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/StringField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/TitleField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/TitleField'>;
}
declare module 'react-jsonschema-form/lib/components/fields/UnsupportedField.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/fields/UnsupportedField'>;
}
declare module 'react-jsonschema-form/lib/components/Form.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/Form'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/AltDateTimeWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/AltDateTimeWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/AltDateWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/AltDateWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/BaseInput.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/BaseInput'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/CheckboxesWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/CheckboxesWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/CheckboxWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/CheckboxWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/ColorWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/ColorWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/DateTimeWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/DateTimeWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/DateWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/DateWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/EmailWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/EmailWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/FileWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/FileWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/HiddenWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/HiddenWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/index.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/index'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/PasswordWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/PasswordWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/RadioWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/RadioWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/RangeWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/RangeWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/SelectWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/SelectWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/TextareaWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/TextareaWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/TextWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/TextWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/UpDownWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/UpDownWidget'>;
}
declare module 'react-jsonschema-form/lib/components/widgets/URLWidget.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/components/widgets/URLWidget'>;
}
declare module 'react-jsonschema-form/lib/index.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/index'>;
}
declare module 'react-jsonschema-form/lib/utils.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/utils'>;
}
declare module 'react-jsonschema-form/lib/validate.js' {
  declare module.exports: $Exports<'react-jsonschema-form/lib/validate'>;
}
