// flow-typed signature: 8e8cdb1938662d6e2c62a1adb4e1b028
// flow-typed version: <<STUB>>/react-transform-catch-errors_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transform-catch-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transform-catch-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transform-catch-errors/lib/index' {
  declare module.exports: any;
}

declare module 'react-transform-catch-errors/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transform-catch-errors/lib/index.js' {
  declare module.exports: $Exports<'react-transform-catch-errors/lib/index'>;
}
declare module 'react-transform-catch-errors/src/index.js' {
  declare module.exports: $Exports<'react-transform-catch-errors/src/index'>;
}
