// flow-typed signature: a0b606dd0cbbebf5e7163d0a643b77fd
// flow-typed version: <<STUB>>/toctoc_v^0.2.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toctoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toctoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toctoc/bin/toctoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toctoc/bin/toctoc.js' {
  declare module.exports: $Exports<'toctoc/bin/toctoc'>;
}
