/* @flow */
export const PLUGIN_CONFIRM_REVIEW_REQUEST = "PLUGIN_CONFIRM_REVIEW_REQUEST";
export const PLUGIN_REVIEW_REQUEST = "PLUGIN_REVIEW_REQUEST";
export const PLUGIN_CONFIRM_DECLINE_CHANGES = "PLUGIN_CONFIRM_DECLINE_CHANGES";
export const PLUGIN_DECLINE_REQUEST = "PLUGIN_DECLINE_REQUEST";
export const PLUGIN_SIGNOFF_REQUEST = "PLUGIN_SIGNOFF_REQUEST";
export const PLUGIN_CANCEL_PENDING_CONFIRM = "PLUGIN_CANCEL_PENDING_CONFIRM";
export const SIGNOFF_WORKFLOW_INFO = "SIGNOFF_WORKFLOW_INFO";
