export const BUCKET_BUSY = "BUCKET_BUSY";
export const BUCKET_RESET = "BUCKET_RESET";
export const BUCKET_LOAD_REQUEST = "BUCKET_LOAD_REQUEST";
export const BUCKET_LOAD_SUCCESS = "BUCKET_LOAD_SUCCESS";
export const BUCKET_CREATE_REQUEST = "BUCKET_CREATE_REQUEST";
export const BUCKET_UPDATE_REQUEST = "BUCKET_UPDATE_REQUEST";
export const BUCKET_DELETE_REQUEST = "BUCKET_DELETE_REQUEST";

export const COLLECTION_BUSY = "COLLECTION_BUSY";
export const COLLECTION_RESET = "COLLECTION_RESET";
export const COLLECTION_LOAD_REQUEST = "COLLECTION_LOAD_REQUEST";
export const COLLECTION_LOAD_SUCCESS = "COLLECTION_LOAD_SUCCESS";
export const COLLECTION_CREATE_REQUEST = "COLLECTION_CREATE_REQUEST";
export const COLLECTION_UPDATE_REQUEST = "COLLECTION_UPDATE_REQUEST";
export const COLLECTION_DELETE_REQUEST = "COLLECTION_DELETE_REQUEST";
export const COLLECTION_RECORDS_REQUEST = "COLLECTION_RECORDS_REQUEST";
export const COLLECTION_RECORDS_SUCCESS = "COLLECTION_RECORDS_SUCCESS";

export const NOTIFICATION_ADDED = "NOTIFICATION_ADDED";
export const NOTIFICATION_REMOVED = "NOTIFICATION_REMOVED";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";

export const RECORD_LOAD_REQUEST = "RECORD_LOAD_REQUEST";
export const RECORD_LOAD_SUCCESS = "RECORD_LOAD_SUCCESS";
export const RECORD_CREATE_REQUEST = "RECORD_CREATE_REQUEST";
export const RECORD_UPDATE_REQUEST = "RECORD_UPDATE_REQUEST";
export const RECORD_DELETE_REQUEST = "RECORD_DELETE_REQUEST";
export const RECORD_BULK_CREATE_REQUEST = "RECORD_BULK_CREATE_REQUEST";
export const RECORD_RESET = "RECORD_RESET";

export const ROUTE_LOAD_REQUEST = "ROUTE_LOAD_REQUEST";
export const ROUTE_LOAD_SUCCESS = "ROUTE_LOAD_SUCCESS";

export const SESSION_BUCKETS_REQUEST = "SESSION_BUCKETS_REQUEST";
export const SESSION_BUCKETS_SUCCESS = "SESSION_BUCKETS_SUCCESS";
export const SESSION_BUSY = "SESSION_BUSY";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_SERVERINFO_SUCCESS = "SESSION_SERVERINFO_SUCCESS";
export const SESSION_SETUP = "SESSION_SETUP";
export const SESSION_SETUP_COMPLETE = "SESSION_SETUP_COMPLETE";
