export const CLIENT_BUSY = "CLIENT_BUSY";

export const COLLECTION_RESET = "COLLECTION_RESET";
export const COLLECTION_CREATE_REQUEST = "COLLECTION_CREATE_REQUEST";
export const COLLECTION_DELETE_REQUEST = "COLLECTION_DELETE_REQUEST";
export const COLLECTION_LOAD_REQUEST = "COLLECTION_LOAD_REQUEST";
export const COLLECTION_LOAD_SUCCESS = "COLLECTION_LOAD_SUCCESS";
export const COLLECTION_UPDATE_REQUEST = "COLLECTION_UPDATE_REQUEST";
export const COLLECTION_UPDATE_SUCCESS = "COLLECTION_UPDATE_SUCCESS";
export const COLLECTION_RECORDS_LOADED = "COLLECTION_RECORDS_LOADED";
export const COLLECTION_RECORD_CREATED = "COLLECTION_RECORD_CREATED";

export const NOTIFICATION_ADDED = "NOTIFICATION_ADDED";
export const NOTIFICATION_REMOVED = "NOTIFICATION_REMOVED";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";

export const RECORD_LOADED = "RECORD_LOADED";
export const RECORD_RESET = "RECORD_RESET";

export const SESSION_BUCKETS_REQUEST = "SESSION_BUCKETS_REQUEST";
export const SESSION_BUCKETS_SUCCESS = "SESSION_BUCKETS_SUCCESS";
export const SESSION_BUCKETS_FAILURE = "SESSION_BUCKETS_FAILURE";
export const SESSION_BUSY = "SESSION_BUSY";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_SERVERINFO_SUCCESS = "SESSION_SERVERINFO_SUCCESS";
export const SESSION_SERVERINFO_FAILURE = "SESSION_SERVERINFO_FAILURE";
export const SESSION_SETUP = "SESSION_SETUP";
export const SESSION_SETUP_COMPLETE = "SESSION_SETUP_COMPLETE";
