export const DEFAULT_KINTO_SERVER = "https://demo.kinto-storage.org/v1/";
export const ANONYMOUS_AUTH = "anonymous";
export const MAX_PER_PAGE = 200;
export const DEFAULT_SORT = "-last_modified";
export const SINGLE_SERVER = import.meta.env.KINTO_ADMIN_SINGLE_SERVER
  ? document.location.toString().split("/admin/")[0]
  : null;
export const SIDEBAR_MAX_LISTED_COLLECTIONS = 10;

export const ATTACHMENT_DELETE_REQUEST = "ATTACHMENT_DELETE_REQUEST";

export const BUCKET_UPDATE_REQUEST = "BUCKET_UPDATE_REQUEST";
export const BUCKET_DELETE_REQUEST = "BUCKET_DELETE_REQUEST";

export const COLLECTION_UPDATE_REQUEST = "COLLECTION_UPDATE_REQUEST";
export const COLLECTION_DELETE_REQUEST = "COLLECTION_DELETE_REQUEST";

export const HEARTBEAT_REQUEST = "HEARTBEAT_REQUEST";
export const HEARTBEAT_RESPONSE = "HEARTBEAT_RESPONSE";

export const SESSION_AUTHENTICATED = "SESSION_AUTHENTICATED";
export const SESSION_AUTHENTICATION_FAILED = "SESSION_AUTHENTICATION_FAILED";
export const SESSION_BUCKETS_REQUEST = "SESSION_BUCKETS_REQUEST";
export const SESSION_BUCKETS_SUCCESS = "SESSION_BUCKETS_SUCCESS";
export const SESSION_BUSY = "SESSION_BUSY";
export const SESSION_COPY_AUTHENTICATION_HEADER =
  "SESSION_COPY_AUTHENTICATION_HEADER";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_SERVER_CHANGE = "SESSION_SERVER_CHANGE";
export const SESSION_GET_SERVERINFO = "SESSION_GET_SERVERINFO";
export const SESSION_SERVERINFO_SUCCESS = "SESSION_SERVERINFO_SUCCESS";
export const SESSION_PERMISSIONS_SUCCESS = "SESSION_PERMISSIONS_SUCCESS";
export const SESSION_SETUP = "SESSION_SETUP";
export const SESSION_SETUP_COMPLETE = "SESSION_SETUP_COMPLETE";
export const SESSION_STORE_REDIRECT_URL = "SESSION_STORE_REDIRECT_URL";

export const SIGNOFF_CONFIRM_REVIEW_REQUEST = "SIGNOFF_CONFIRM_REVIEW_REQUEST";
export const SIGNOFF_REVIEW_REQUEST = "SIGNOFF_REVIEW_REQUEST";
export const SIGNOFF_CONFIRM_ROLLBACK_CHANGES =
  "SIGNOFF_CONFIRM_ROLLBACK_CHANGES";
export const SIGNOFF_ROLLBACK_CHANGES = "SIGNOFF_ROLLBACK_CHANGES";
export const SIGNOFF_CONFIRM_DECLINE_CHANGES =
  "SIGNOFF_CONFIRM_DECLINE_CHANGES";
export const SIGNOFF_DECLINE_REQUEST = "SIGNOFF_DECLINE_REQUEST";
export const SIGNOFF_SIGNOFF_REQUEST = "SIGNOFF_SIGNOFF_REQUEST";
export const SIGNOFF_CANCEL_PENDING_CONFIRM = "SIGNOFF_CANCEL_PENDING_CONFIRM";
export const SIGNOFF_WORKFLOW_INFO = "SIGNOFF_WORKFLOW_INFO";
export const SIGNOFF_DECLINE_AND_DISCARD_REQUEST =
  "SIGNOFF_DECLINE_AND_DISCARD_REQUEST";
