on:
  push:
    branches:
      - master
  pull_request:

name: Browser Test
jobs:
  chore:
    name: Testing from a browser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start
        run: |
          cd build/
          npx http-server -p 3000 &

      - name: Check bundle
        run: curl --head --fail http://localhost:3000/bundle.js

      - name: geckodriver/firefox
        run: |
          echo "geckodriver/firefox"
          which geckodriver
          geckodriver --version
          which firefox
          firefox --version

      - name: Browser Tests
        run: |
          npm run test:browser
