on:
  push:
    branches:
      - master
  pull_request:

name: Build
jobs:
  chore:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npm run build:lib
