on:
  push:
    branches:
      - master
  pull_request:

name: Code Style
jobs:
  chore:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Install Node dependencies
        run: npm ci

      - name: Code Style
        run: |
          npm run cs-check

      - name: Lint
        run: |
          npm run lint
