on:
  push:
    branches:
      - master
  pull_request:

name: Windows Integration
jobs:
  chore:
    name: Testing on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print environment
        run: |
          node --version
          npm --version
          python --version
          pip --version
      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npm run build:lib

      - name: Run tests
        run: npm test
